# Generated by Django 2.0.7 on 2018-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=20)),
                ('article_context', models.TextField()),
            ],
        ),
    ]
